// Auto-generated. Do not edit!

// (in-package print_server.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PrintFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.nr_completed_prints = null;
    }
    else {
      if (initObj.hasOwnProperty('nr_completed_prints')) {
        this.nr_completed_prints = initObj.nr_completed_prints
      }
      else {
        this.nr_completed_prints = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PrintFeedback
    // Serialize message field [nr_completed_prints]
    bufferOffset = _serializer.float32(obj.nr_completed_prints, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PrintFeedback
    let len;
    let data = new PrintFeedback(null);
    // Deserialize message field [nr_completed_prints]
    data.nr_completed_prints = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'print_server/PrintFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '8a599b64b8e035fab93aa2dd1842fea9';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    float32 nr_completed_prints
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PrintFeedback(null);
    if (msg.nr_completed_prints !== undefined) {
      resolved.nr_completed_prints = msg.nr_completed_prints;
    }
    else {
      resolved.nr_completed_prints = 0.0
    }

    return resolved;
    }
};

module.exports = PrintFeedback;
