// Auto-generated. Do not edit!

// (in-package print_server.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PrintGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.print_nr_times = null;
    }
    else {
      if (initObj.hasOwnProperty('print_nr_times')) {
        this.print_nr_times = initObj.print_nr_times
      }
      else {
        this.print_nr_times = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PrintGoal
    // Serialize message field [print_nr_times]
    bufferOffset = _serializer.uint32(obj.print_nr_times, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PrintGoal
    let len;
    let data = new PrintGoal(null);
    // Deserialize message field [print_nr_times]
    data.print_nr_times = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'print_server/PrintGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3f890709095ea5967b10b9b6490a682c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    uint32 print_nr_times  # How many times the action prints
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PrintGoal(null);
    if (msg.print_nr_times !== undefined) {
      resolved.print_nr_times = msg.print_nr_times;
    }
    else {
      resolved.print_nr_times = 0
    }

    return resolved;
    }
};

module.exports = PrintGoal;
