// Auto-generated. Do not edit!

// (in-package print_server.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PrintResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.print_success = null;
    }
    else {
      if (initObj.hasOwnProperty('print_success')) {
        this.print_success = initObj.print_success
      }
      else {
        this.print_success = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PrintResult
    // Serialize message field [print_success]
    bufferOffset = _serializer.bool(obj.print_success, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PrintResult
    let len;
    let data = new PrintResult(null);
    // Deserialize message field [print_success]
    data.print_success = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'print_server/PrintResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '57c754efdeda0c1209812dae0350c80f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    bool print_success
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PrintResult(null);
    if (msg.print_success !== undefined) {
      resolved.print_success = msg.print_success;
    }
    else {
      resolved.print_success = false
    }

    return resolved;
    }
};

module.exports = PrintResult;
