// Generated by gencpp from file print_server/PrintFeedback.msg
// DO NOT EDIT!


#ifndef PRINT_SERVER_MESSAGE_PRINTFEEDBACK_H
#define PRINT_SERVER_MESSAGE_PRINTFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace print_server
{
template <class ContainerAllocator>
struct PrintFeedback_
{
  typedef PrintFeedback_<ContainerAllocator> Type;

  PrintFeedback_()
    : nr_completed_prints(0.0)  {
    }
  PrintFeedback_(const ContainerAllocator& _alloc)
    : nr_completed_prints(0.0)  {
  (void)_alloc;
    }



   typedef float _nr_completed_prints_type;
  _nr_completed_prints_type nr_completed_prints;





  typedef boost::shared_ptr< ::print_server::PrintFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::print_server::PrintFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct PrintFeedback_

typedef ::print_server::PrintFeedback_<std::allocator<void> > PrintFeedback;

typedef boost::shared_ptr< ::print_server::PrintFeedback > PrintFeedbackPtr;
typedef boost::shared_ptr< ::print_server::PrintFeedback const> PrintFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::print_server::PrintFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::print_server::PrintFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace print_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'print_server': ['/home/user/Desktop/master/devel/share/print_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::print_server::PrintFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::print_server::PrintFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::print_server::PrintFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::print_server::PrintFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::print_server::PrintFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::print_server::PrintFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::print_server::PrintFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a599b64b8e035fab93aa2dd1842fea9";
  }

  static const char* value(const ::print_server::PrintFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a599b64b8e035faULL;
  static const uint64_t static_value2 = 0xb93aa2dd1842fea9ULL;
};

template<class ContainerAllocator>
struct DataType< ::print_server::PrintFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "print_server/PrintFeedback";
  }

  static const char* value(const ::print_server::PrintFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::print_server::PrintFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
float32 nr_completed_prints\n\
";
  }

  static const char* value(const ::print_server::PrintFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::print_server::PrintFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nr_completed_prints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PrintFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::print_server::PrintFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::print_server::PrintFeedback_<ContainerAllocator>& v)
  {
    s << indent << "nr_completed_prints: ";
    Printer<float>::stream(s, indent + "  ", v.nr_completed_prints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRINT_SERVER_MESSAGE_PRINTFEEDBACK_H
