// Generated by gencpp from file print_server/PrintResult.msg
// DO NOT EDIT!


#ifndef PRINT_SERVER_MESSAGE_PRINTRESULT_H
#define PRINT_SERVER_MESSAGE_PRINTRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace print_server
{
template <class ContainerAllocator>
struct PrintResult_
{
  typedef PrintResult_<ContainerAllocator> Type;

  PrintResult_()
    : print_success(false)  {
    }
  PrintResult_(const ContainerAllocator& _alloc)
    : print_success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _print_success_type;
  _print_success_type print_success;





  typedef boost::shared_ptr< ::print_server::PrintResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::print_server::PrintResult_<ContainerAllocator> const> ConstPtr;

}; // struct PrintResult_

typedef ::print_server::PrintResult_<std::allocator<void> > PrintResult;

typedef boost::shared_ptr< ::print_server::PrintResult > PrintResultPtr;
typedef boost::shared_ptr< ::print_server::PrintResult const> PrintResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::print_server::PrintResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::print_server::PrintResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace print_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'print_server': ['/home/user/Desktop/master/devel/share/print_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::print_server::PrintResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::print_server::PrintResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::print_server::PrintResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::print_server::PrintResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::print_server::PrintResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::print_server::PrintResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::print_server::PrintResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57c754efdeda0c1209812dae0350c80f";
  }

  static const char* value(const ::print_server::PrintResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57c754efdeda0c12ULL;
  static const uint64_t static_value2 = 0x09812dae0350c80fULL;
};

template<class ContainerAllocator>
struct DataType< ::print_server::PrintResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "print_server/PrintResult";
  }

  static const char* value(const ::print_server::PrintResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::print_server::PrintResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
bool print_success\n\
";
  }

  static const char* value(const ::print_server::PrintResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::print_server::PrintResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.print_success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PrintResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::print_server::PrintResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::print_server::PrintResult_<ContainerAllocator>& v)
  {
    s << indent << "print_success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.print_success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRINT_SERVER_MESSAGE_PRINTRESULT_H
