// Generated by gencpp from file master/state.msg
// DO NOT EDIT!


#ifndef MASTER_MESSAGE_STATE_H
#define MASTER_MESSAGE_STATE_H

#include <ros/service_traits.h>


#include <master/stateRequest.h>
#include <master/stateResponse.h>


namespace master
{

struct state
{

typedef stateRequest Request;
typedef stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct state
} // namespace master


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master::state > {
  static const char* value()
  {
    return "fc356054cc550c7695fed3a501922336";
  }

  static const char* value(const ::master::state&) { return value(); }
};

template<>
struct DataType< ::master::state > {
  static const char* value()
  {
    return "master/state";
  }

  static const char* value(const ::master::state&) { return value(); }
};


// service_traits::MD5Sum< ::master::stateRequest> should match 
// service_traits::MD5Sum< ::master::state > 
template<>
struct MD5Sum< ::master::stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master::state >::value();
  }
  static const char* value(const ::master::stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master::stateRequest> should match 
// service_traits::DataType< ::master::state > 
template<>
struct DataType< ::master::stateRequest>
{
  static const char* value()
  {
    return DataType< ::master::state >::value();
  }
  static const char* value(const ::master::stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master::stateResponse> should match 
// service_traits::MD5Sum< ::master::state > 
template<>
struct MD5Sum< ::master::stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master::state >::value();
  }
  static const char* value(const ::master::stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master::stateResponse> should match 
// service_traits::DataType< ::master::state > 
template<>
struct DataType< ::master::stateResponse>
{
  static const char* value()
  {
    return DataType< ::master::state >::value();
  }
  static const char* value(const ::master::stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_MESSAGE_STATE_H
