// Generated by gencpp from file master/stateResponse.msg
// DO NOT EDIT!


#ifndef MASTER_MESSAGE_STATERESPONSE_H
#define MASTER_MESSAGE_STATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace master
{
template <class ContainerAllocator>
struct stateResponse_
{
  typedef stateResponse_<ContainerAllocator> Type;

  stateResponse_()
    : robot1_finished(false)  {
    }
  stateResponse_(const ContainerAllocator& _alloc)
    : robot1_finished(false)  {
  (void)_alloc;
    }



   typedef uint8_t _robot1_finished_type;
  _robot1_finished_type robot1_finished;





  typedef boost::shared_ptr< ::master::stateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master::stateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct stateResponse_

typedef ::master::stateResponse_<std::allocator<void> > stateResponse;

typedef boost::shared_ptr< ::master::stateResponse > stateResponsePtr;
typedef boost::shared_ptr< ::master::stateResponse const> stateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master::stateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master::stateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace master

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::master::stateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master::stateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master::stateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master::stateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master::stateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master::stateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master::stateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34476f89daf3bba091c2d9ef0c5b6b5b";
  }

  static const char* value(const ::master::stateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34476f89daf3bba0ULL;
  static const uint64_t static_value2 = 0x91c2d9ef0c5b6b5bULL;
};

template<class ContainerAllocator>
struct DataType< ::master::stateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master/stateResponse";
  }

  static const char* value(const ::master::stateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master::stateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool robot1_finished\n\
\n\
";
  }

  static const char* value(const ::master::stateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master::stateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot1_finished);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master::stateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::master::stateResponse_<ContainerAllocator>& v)
  {
    s << indent << "robot1_finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.robot1_finished);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_MESSAGE_STATERESPONSE_H
