// Generated by gencpp from file master/stateRequest.msg
// DO NOT EDIT!


#ifndef MASTER_MESSAGE_STATEREQUEST_H
#define MASTER_MESSAGE_STATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace master
{
template <class ContainerAllocator>
struct stateRequest_
{
  typedef stateRequest_<ContainerAllocator> Type;

  stateRequest_()
    : execute_state(false)  {
    }
  stateRequest_(const ContainerAllocator& _alloc)
    : execute_state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _execute_state_type;
  _execute_state_type execute_state;





  typedef boost::shared_ptr< ::master::stateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master::stateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct stateRequest_

typedef ::master::stateRequest_<std::allocator<void> > stateRequest;

typedef boost::shared_ptr< ::master::stateRequest > stateRequestPtr;
typedef boost::shared_ptr< ::master::stateRequest const> stateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master::stateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master::stateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace master

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'master': ['/home/user/Desktop/master/src/master_node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::master::stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master::stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master::stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master::stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master::stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master::stateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master::stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27587b439c805f63a7377ee4a1dcf7d5";
  }

  static const char* value(const ::master::stateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27587b439c805f63ULL;
  static const uint64_t static_value2 = 0xa7377ee4a1dcf7d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::master::stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master/stateRequest";
  }

  static const char* value(const ::master::stateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master::stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool execute_state\n\
";
  }

  static const char* value(const ::master::stateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master::stateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.execute_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master::stateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::master::stateRequest_<ContainerAllocator>& v)
  {
    s << indent << "execute_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.execute_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_MESSAGE_STATEREQUEST_H
