(cl:defpackage server_test-msg
  (:use )
  (:export
   "<SERVERTESTACTION>"
   "SERVERTESTACTION"
   "<SERVERTESTACTIONFEEDBACK>"
   "SERVERTESTACTIONFEEDBACK"
   "<SERVERTESTACTIONGOAL>"
   "SERVERTESTACTIONGOAL"
   "<SERVERTESTACTIONRESULT>"
   "SERVERTESTACTIONRESULT"
   "<SERVERTESTFEEDBACK>"
   "SERVERTESTFEEDBACK"
   "<SERVERTESTGOAL>"
   "SERVERTESTGOAL"
   "<SERVERTESTRESULT>"
   "SERVERTESTRESULT"
  ))

