; Auto-generated. Do not edit!


(cl:in-package server_test-msg)


;//! \htmlinclude servertestFeedback.msg.html

(cl:defclass <servertestFeedback> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass servertestFeedback (<servertestFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <servertestFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'servertestFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name server_test-msg:<servertestFeedback> is deprecated: use server_test-msg:servertestFeedback instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <servertestFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader server_test-msg:success-val is deprecated.  Use server_test-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <servertestFeedback>) ostream)
  "Serializes a message object of type '<servertestFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <servertestFeedback>) istream)
  "Deserializes a message object of type '<servertestFeedback>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<servertestFeedback>)))
  "Returns string type for a message object of type '<servertestFeedback>"
  "server_test/servertestFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'servertestFeedback)))
  "Returns string type for a message object of type 'servertestFeedback"
  "server_test/servertestFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<servertestFeedback>)))
  "Returns md5sum for a message object of type '<servertestFeedback>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'servertestFeedback)))
  "Returns md5sum for a message object of type 'servertestFeedback"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<servertestFeedback>)))
  "Returns full string definition for message of type '<servertestFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'servertestFeedback)))
  "Returns full string definition for message of type 'servertestFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <servertestFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <servertestFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'servertestFeedback
    (cl:cons ':success (success msg))
))
