(cl:defpackage print_server-msg
  (:use )
  (:export
   "<PRINTACTION>"
   "PRINTACTION"
   "<PRINTACTIONFEEDBACK>"
   "PRINTACTIONFEEDBACK"
   "<PRINTACTIONGOAL>"
   "PRINTACTIONGOAL"
   "<PRINTACTIONRESULT>"
   "PRINTACTIONRESULT"
   "<PRINTFEEDBACK>"
   "PRINTFEEDBACK"
   "<PRINTGOAL>"
   "PRINTGOAL"
   "<PRINTRESULT>"
   "PRINTRESULT"
  ))

