; Auto-generated. Do not edit!


(cl:in-package print_server-msg)


;//! \htmlinclude PrintFeedback.msg.html

(cl:defclass <PrintFeedback> (roslisp-msg-protocol:ros-message)
  ((nr_completed_prints
    :reader nr_completed_prints
    :initarg :nr_completed_prints
    :type cl:float
    :initform 0.0))
)

(cl:defclass PrintFeedback (<PrintFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PrintFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PrintFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name print_server-msg:<PrintFeedback> is deprecated: use print_server-msg:PrintFeedback instead.")))

(cl:ensure-generic-function 'nr_completed_prints-val :lambda-list '(m))
(cl:defmethod nr_completed_prints-val ((m <PrintFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader print_server-msg:nr_completed_prints-val is deprecated.  Use print_server-msg:nr_completed_prints instead.")
  (nr_completed_prints m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PrintFeedback>) ostream)
  "Serializes a message object of type '<PrintFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'nr_completed_prints))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PrintFeedback>) istream)
  "Deserializes a message object of type '<PrintFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'nr_completed_prints) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PrintFeedback>)))
  "Returns string type for a message object of type '<PrintFeedback>"
  "print_server/PrintFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PrintFeedback)))
  "Returns string type for a message object of type 'PrintFeedback"
  "print_server/PrintFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PrintFeedback>)))
  "Returns md5sum for a message object of type '<PrintFeedback>"
  "8a599b64b8e035fab93aa2dd1842fea9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PrintFeedback)))
  "Returns md5sum for a message object of type 'PrintFeedback"
  "8a599b64b8e035fab93aa2dd1842fea9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PrintFeedback>)))
  "Returns full string definition for message of type '<PrintFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 nr_completed_prints~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PrintFeedback)))
  "Returns full string definition for message of type 'PrintFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 nr_completed_prints~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PrintFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PrintFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PrintFeedback
    (cl:cons ':nr_completed_prints (nr_completed_prints msg))
))
