; Auto-generated. Do not edit!


(cl:in-package print_server-msg)


;//! \htmlinclude PrintActionGoal.msg.html

(cl:defclass <PrintActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type print_server-msg:PrintGoal
    :initform (cl:make-instance 'print_server-msg:PrintGoal)))
)

(cl:defclass PrintActionGoal (<PrintActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PrintActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PrintActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name print_server-msg:<PrintActionGoal> is deprecated: use print_server-msg:PrintActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <PrintActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader print_server-msg:header-val is deprecated.  Use print_server-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <PrintActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader print_server-msg:goal_id-val is deprecated.  Use print_server-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <PrintActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader print_server-msg:goal-val is deprecated.  Use print_server-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PrintActionGoal>) ostream)
  "Serializes a message object of type '<PrintActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PrintActionGoal>) istream)
  "Deserializes a message object of type '<PrintActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PrintActionGoal>)))
  "Returns string type for a message object of type '<PrintActionGoal>"
  "print_server/PrintActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PrintActionGoal)))
  "Returns string type for a message object of type 'PrintActionGoal"
  "print_server/PrintActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PrintActionGoal>)))
  "Returns md5sum for a message object of type '<PrintActionGoal>"
  "ce42dcc333f7aa67a72865409d761e2c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PrintActionGoal)))
  "Returns md5sum for a message object of type 'PrintActionGoal"
  "ce42dcc333f7aa67a72865409d761e2c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PrintActionGoal>)))
  "Returns full string definition for message of type '<PrintActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%PrintGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: print_server/PrintGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 print_nr_times  # How many times the action prints~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PrintActionGoal)))
  "Returns full string definition for message of type 'PrintActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%PrintGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: print_server/PrintGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 print_nr_times  # How many times the action prints~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PrintActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PrintActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PrintActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
