; Auto-generated. Do not edit!


(cl:in-package print_server-msg)


;//! \htmlinclude PrintGoal.msg.html

(cl:defclass <PrintGoal> (roslisp-msg-protocol:ros-message)
  ((print_nr_times
    :reader print_nr_times
    :initarg :print_nr_times
    :type cl:integer
    :initform 0))
)

(cl:defclass PrintGoal (<PrintGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PrintGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PrintGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name print_server-msg:<PrintGoal> is deprecated: use print_server-msg:PrintGoal instead.")))

(cl:ensure-generic-function 'print_nr_times-val :lambda-list '(m))
(cl:defmethod print_nr_times-val ((m <PrintGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader print_server-msg:print_nr_times-val is deprecated.  Use print_server-msg:print_nr_times instead.")
  (print_nr_times m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PrintGoal>) ostream)
  "Serializes a message object of type '<PrintGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'print_nr_times)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'print_nr_times)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'print_nr_times)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'print_nr_times)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PrintGoal>) istream)
  "Deserializes a message object of type '<PrintGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'print_nr_times)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'print_nr_times)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'print_nr_times)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'print_nr_times)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PrintGoal>)))
  "Returns string type for a message object of type '<PrintGoal>"
  "print_server/PrintGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PrintGoal)))
  "Returns string type for a message object of type 'PrintGoal"
  "print_server/PrintGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PrintGoal>)))
  "Returns md5sum for a message object of type '<PrintGoal>"
  "3f890709095ea5967b10b9b6490a682c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PrintGoal)))
  "Returns md5sum for a message object of type 'PrintGoal"
  "3f890709095ea5967b10b9b6490a682c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PrintGoal>)))
  "Returns full string definition for message of type '<PrintGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 print_nr_times  # How many times the action prints~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PrintGoal)))
  "Returns full string definition for message of type 'PrintGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 print_nr_times  # How many times the action prints~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PrintGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PrintGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PrintGoal
    (cl:cons ':print_nr_times (print_nr_times msg))
))
