; Auto-generated. Do not edit!


(cl:in-package print_server-msg)


;//! \htmlinclude PrintResult.msg.html

(cl:defclass <PrintResult> (roslisp-msg-protocol:ros-message)
  ((print_success
    :reader print_success
    :initarg :print_success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass PrintResult (<PrintResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PrintResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PrintResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name print_server-msg:<PrintResult> is deprecated: use print_server-msg:PrintResult instead.")))

(cl:ensure-generic-function 'print_success-val :lambda-list '(m))
(cl:defmethod print_success-val ((m <PrintResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader print_server-msg:print_success-val is deprecated.  Use print_server-msg:print_success instead.")
  (print_success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PrintResult>) ostream)
  "Serializes a message object of type '<PrintResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'print_success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PrintResult>) istream)
  "Deserializes a message object of type '<PrintResult>"
    (cl:setf (cl:slot-value msg 'print_success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PrintResult>)))
  "Returns string type for a message object of type '<PrintResult>"
  "print_server/PrintResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PrintResult)))
  "Returns string type for a message object of type 'PrintResult"
  "print_server/PrintResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PrintResult>)))
  "Returns md5sum for a message object of type '<PrintResult>"
  "57c754efdeda0c1209812dae0350c80f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PrintResult)))
  "Returns md5sum for a message object of type 'PrintResult"
  "57c754efdeda0c1209812dae0350c80f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PrintResult>)))
  "Returns full string definition for message of type '<PrintResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool print_success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PrintResult)))
  "Returns full string definition for message of type 'PrintResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool print_success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PrintResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PrintResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PrintResult
    (cl:cons ':print_success (print_success msg))
))
